### ISSUE TITLE
views/posts/edit.html.erb

### ISSUE THREAD

**Issue by ryanmanchester** [learn-co-curriculum/validations-with-form_tag-rails-lab#8]
The tests for invalid information do not pass not matter what. I even copied the solution from GitHub into my text editor and got the same errors I was getting. Thanks!

Ryan

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
